owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0046afed-feba-49ae-83fb-df84c38e0d5e"
min = [ -368, -2147483648, -432 ]
max = [ -273, 2147483647, -353 ]
name = "TeaCon 2022 展示服务器 6f 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
