owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0002b3c7-3aa1-4dc5-93b9-efc1e30d343e"
min = [ -112, -2147483648, -256 ]
max = [ -33, 2147483647, -209 ]
name = "TeaCon 2022 展示服务器 1c 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
