owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "003cb99d-0225-453b-bc11-8347c09b9cb6"
min = [ -432, -2147483648, -16 ]
max = [ -337, 2147483647, 47 ]
name = "TeaCon 2022 展示服务器 5q 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
