owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0040ed98-3d6e-4df9-80ac-a0ac93a09c7a"
min = [ -384, -2147483648, 224 ]
max = [ -321, 2147483647, 303 ]
name = "TeaCon 2022 展示服务器 5u 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
