owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0031c07a-d595-480a-8eaa-3ef5104ed3c5"
min = [ -320, -2147483648, 400 ]
max = [ -225, 2147483647, 479 ]
name = "TeaCon 2022 展示服务器 5f 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
