owner = "00000000-0000-0000-0000-000000000000"
uid = "6ac53e6d-2e9b-4704-a296-6791dd0b5619"
min = [ -2147483648, -2147483648, -2147483648 ]
max = [ 2147483647, 2147483647, 2147483647 ]
name = "TeaCon 2022 展示服务器"
dimension = "minecraft:overworld"
friends = []

# Remember to disable some of these checks when we are ready
[properties]
"area.allow_activate_block" = "true"
"area.allow_click_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_activate_block.ashihara:pail" = false
"area.allow_spawn" = "true"
"area.allow_spawn.xkdeco" = true
"area.allow_spawn.mtr" = true
"area.allow_spawn.minecraft" = true
"area.allow_spawn.kitchenkarrot:can" = true
"area.allow_spawn.minecraft:tnt" = false
"area.allow_spawn.tactical_cards" = false
"area.allow_possess.tactical_cards" = false
"area.allow_use_item.tactical_cards" = false
"area.allow_use_item.torchikoma:torch_launcher" = false
"area.allow_use_item.torchikoma:torch_gatling" = false
"area.allow_use_item.torchikoma:torch_cannon" = false
"area.allow_use_item" = "true"
"area.allow_pvp" = "false"
"area.allow_attack" = "true"
"area.allow_attack.minecraft:item_frame" = false
"area.allow_attack.minecraft:painting" = false
"area.allow_attack.minecraft:armor_stand" = false
"area.allow_fire_spread" = false
"area.display_welcome_message" = true
"area.allow_explosion" = false
"area.allow_explosion_affect_blocks" = false
"area.allow_explosion_affect_entities" = false