owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "003bd6cf-d555-40de-962e-1a8fd2d76f1b"
min = [ -304, -2147483648, -64 ]
max = [ -241, 2147483647, -1 ]
name = "TeaCon 2022 展示服务器 5p 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
