owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "002bcca5-7d0f-4d3a-aaf7-dbc2b84ba8a4"
min = [ 0, -2147483648, 256 ]
max = [ 63, 2147483647, 319 ]
name = "TeaCon 2022 展示服务器 4j 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
