owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0044b768-72bb-468e-8e72-333fac07c99f"
min = [ -464, -2147483648, -368 ]
max = [ -385, 2147483647, -273 ]
name = "TeaCon 2022 展示服务器 6d 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
