owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0007c065-a248-483d-979c-01015ad24107"
min = [ -176, -2147483648, -432 ]
max = [ -81, 2147483647, -353 ]
name = "TeaCon 2022 展示服务器 1h 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
