owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0015ad98-4818-40b4-9fca-86c7e30ee83e"
min = [ -160, -2147483648, 736 ]
max = [ -17, 2147483647, 863 ]
name = "TeaCon 2022 展示服务器 2i 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
