owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0017a78b-441d-4d24-9505-c1b5e7025945"
min = [ 0, -2147483648, 800 ]
max = [ 127, 2147483647, 975 ]
name = "TeaCon 2022 展示服务器 2k 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
