owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0043c2e8-5681-482d-9de0-cc21e185e289"
min = [ -544, -2147483648, 32 ]
max = [ -465, 2147483647, 127 ]
name = "TeaCon 2022 展示服务器 6c 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
