owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "000bcd8c-2594-4d0d-a1ab-ae8aef0dc93a"
min = [ 64, -2147483648, -432 ]
max = [ 143, 2147483647, -369 ]
name = "TeaCon 2022 展示服务器 1l 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
