owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0011b2e0-0414-4e60-99f6-72addb04c2aa"
min = [ 400, -2147483648, -224 ]
max = [ 479, 2147483647, -161 ]
name = "TeaCon 2022 展示服务器 2e 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
