owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0036dffb-69b9-48f7-8516-200ba5dd57c9"
min = [ -448, -2147483648, 544 ]
max = [ -289, 2147483647, 639 ]
name = "TeaCon 2022 展示服务器 5k 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
