owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "002fa9f9-e7a0-482c-bd3f-feb686695b83"
min = [ -224, -2147483648, 320 ]
max = [ -145, 2147483647, 383 ]
name = "TeaCon 2022 展示服务器 5d 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
