owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "000dffca-1dcc-4b71-b096-73cde7918f26"
min = [ 224, -2147483648, -288 ]
max = [ 287, 2147483647, -225 ]
name = "TeaCon 2022 展示服务器 2a 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
