owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0014dd90-5960-4e26-aff6-afe54c9f78c6"
min = [ -224, -2147483648, 592 ]
max = [ -97, 2147483647, 719 ]
name = "TeaCon 2022 展示服务器 2h 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
