owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0048f940-14e4-48ea-a661-3714c8aea77e"
min = [ 208, -2147483648, -528 ]
max = [ 335, 2147483647, -449 ]
name = "TeaCon 2022 展示服务器 6h 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
