owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0035d164-091d-4f5a-af16-68deb8d2c5d0"
min = [ -416, -2147483648, 656 ]
max = [ -289, 2147483647, 783 ]
name = "TeaCon 2022 展示服务器 5j 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
