owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "003ab962-212b-435f-88cb-4840e917d25e"
min = [ -528, -2147483648, -128 ]
max = [ -417, 2147483647, -65 ]
name = "TeaCon 2022 展示服务器 5o 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
