owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0025e473-ffd4-49a6-94ac-6988bbdce6b7"
min = [ 240, -2147483648, -720 ]
max = [ 367, 2147483647, -593 ]
name = "TeaCon 2022 展示服务器 4d 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
