owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "0022bc1d-0c89-4827-8605-9ddc023b03f8"
min = [ 416, -2147483648, -16 ]
max = [ 495, 2147483647, 79 ]
name = "TeaCon 2022 展示服务器 4a 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_place_block" = "true"
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_break_block" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
