owner = "77718ac3-3223-45ec-88d1-490a03eabafd"
uid = "001ee409-b3fd-4b15-97a5-393dc8af75c7"
min = [ 432, -2147483648, 384 ]
max = [ 575, 2147483647, 511 ]
name = "TeaCon 2022 展示服务器 3g 地块"
dimension = "minecraft:overworld"
friends = []

[properties]
"area.allow_activate_block" = "true"
"area.allow_interact_entity" = "true"
"area.allow_use_item" = "true"
"area.allow_interact_entity_specific" = "true"
"area.allow_click_block" = "true"
