name = "builder_emberphoenix"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "0027e75b-d344-4735-87ad-1f98fba707f1"

[[permissions]]
permission = "area_control.*"
value = true

[permissions.context]
world = "world/emberphoenix/phoenix"

[[permissions]]
permission = "weight.10"
value = true

[[permissions]]
permission = "area_control.command.claim.marked"
value = true

[permissions.context]
"area_control:current_area_id" = "0027e75b-d344-4735-87ad-1f98fba707f1"

[[permissions]]
permission = "area_control.command.mark"
value = true

[permissions.context]
"area_control:current_area_id" = "0027e75b-d344-4735-87ad-1f98fba707f1"
