name = "builder_crockpot"

[[permissions]]
permission = "area_control.command.claim.chunk"
value = true

[permissions.context]
"area_control:current_area_id" = "002dfc3b-2ee1-438d-a93a-4421bbde630f"

[[permissions]]
permission = "weight.10"
value = true
