name = "mod"

[[permissions]]
permission = "worldedit.*"
value = true

[[permissions]]
permission = "area_control.*"
value = true

[[permissions]]
permission = "*"
value = true

[[permissions]]
permission = "minecraft.command.gamemode"
value = true

[[permissions]]
permission = "command.gamemode"
value = true

[[permissions]]
permission = "slide_show.interact.projector"
value = true

[[parents]]
group = "builder"
